using System;
namespace Contoso.Sys
{
    [Flags]
    public enum SQLITE
    {
        INVALID = -1,
        OK = 0,
        ERROR = 1,
        INTERNAL = 2,
        PERM = 3,
        ABORT = 4,
        BUSY = 5,
        BUSY_RECOVERY = (BUSY | (1 << 8)),
        LOCKED = 6,
        LOCKED_SHAREDCACHE = (LOCKED | (1 << 8)),
        NOMEM = 7,
        READONLY = 8,
        READONLY_RECOVERY = (READONLY | (1 << 8)),
        READONLY_CANTLOCK = (READONLY | (2 << 8)),
        INTERRUPT = 9,
        IOERR = 10,
        IOERR_READ = (IOERR | (1 << 8)),
        IOERR_SHORT_READ = (IOERR | (2 << 8)),
        IOERR_WRITE = (IOERR | (3 << 8)),
        IOERR_FSYNC = (IOERR | (4 << 8)),
        IOERR_DIR_FSYNC = (IOERR | (5 << 8)),
        IOERR_TRUNCATE = (IOERR | (6 << 8)),
        IOERR_FSTAT = (IOERR | (7 << 8)),
        IOERR_UNLOCK = (IOERR | (8 << 8)),
        IOERR_RDLOCK = (IOERR | (9 << 8)),
        IOERR_DELETE = (IOERR | (10 << 8)),
        IOERR_BLOCKED = (IOERR | (11 << 8)),
        IOERR_NOMEM = (IOERR | (12 << 8)),
        IOERR_ACCESS = (IOERR | (13 << 8)),
        IOERR_CHECKRESERVEDLOCK = (IOERR | (14 << 8)),
        IOERR_LOCK = (IOERR | (15 << 8)),
        IOERR_CLOSE = (IOERR | (16 << 8)),
        IOERR_DIR_CLOSE = (IOERR | (17 << 8)),
        IOERR_SHMOPEN = (IOERR | (18 << 8)),
        IOERR_SHMSIZE = (IOERR | (19 << 8)),
        IOERR_SHMLOCK = (IOERR | (20 << 8)),
        IOERR_SHMMAP = (IOERR | (21 << 8)),
        IOERR_SEEK = (IOERR | (22 << 8)),
        CORRUPT = 11,
        CORRUPT_VTAB = (CORRUPT | (1 << 8)),
        NOTFOUND = 12,
        FULL = 13,
        CANTOPEN = 14,
        CANTOPEN_NOTEMPDIR = (CANTOPEN | (1 << 8)),
        PROTOCOL = 15,
        EMPTY = 16,
        SCHEMA = 17,
        TOOBIG = 18,
        CONSTRAINT = 19,
        MISMATCH = 20,
        MISUSE = 21,
        NOLFS = 22,
        AUTH = 23,
        FORMAT = 24,
        RANGE = 25,
        NOTADB = 26,
        ROW = 100,
        DONE = 101,
    }
}
